### PR TITLE
Active Class and Select Image

### PR DESCRIPTION
**Pull request by firstor**
During the use of this module, I required at least two additional features: 
 * one is CSS class when image is loaded and the preview gets active
 * another one is an API to manually trigger image browser

So in this PR, I try to implement two things myself at my convenient.

_Test was passed with no problem!_

### CODE REVIEW

**Comment by firstor** [comment]
@pinceladasdaweb @lex111 @johndatserakis @DeniseWalter 
Who will review my PR?
I can't see the owner or any participant in the Reviewers list.

Hope to get review and any feedback soon from the repo owner or manager.

Thanks.

**Review by lex111 — APPROVED** [review]
In my opinion, everything is fine :+1:

**Comment by firstor** [comment]
@lex111 When would you release new version? :)

**Comment by lex111** [comment]
@firstor this is a question for @johndatserakis

**Comment by johndatserakis** [comment]
Thank you for the pull-request @firstor. Thank you for reviewing @lex111. Taking a quick peek at it now, should be up shortly.

**Comment by johndatserakis** [comment]
Ok cool, looks good. I'll be pushing the new build to npm now. It'll be v2.0.2. Thanks for the pr! I think the new features make sense for sure.

**Comment by firstor** [comment]
@johndatserakis Thanks for the quick update!

**Pull request merged**
