### PR TITLE
showMultiple option

### PR DESCRIPTION
**Pull request by kozintsev**
I added an option that allows you to display a lot of pictures on the preview.

If it is interesting and useful, you can combine.

### CODE REVIEW

**Comment by johndatserakis** [comment]
Thank you for this - let me review this pull request in the coming days.

**Comment by johndatserakis** [comment]
Nice job on this! Yea I think it looks really good - for others to see, here's a screen shot of it in action:

screen shot 2018-07-19 at 5 15 44 pm

The only issue is there are a few bugs that need to be fixed before I can merge this. At first it's easy to miss - but even a small library like this can get quite complex very quickly, and you can be left with bugs that weren't considered at first.

1. As you can see in the above screenshot, the input label reads that there are 3 files selected. This is the process I did when selecting these images: First, I selected 2 images. Then, I selected 3 more. As you can see, the input label thinks that there is a total of 3. Also, more importantly, the `cachedFileArray` property, in this scenario, only has 3 files in its array. So, for this to be working properly, the count of images that should be shown in the preview grid at that exact moment should have been 3. The code needs to be changed to work like this, or else it could be a big issue for users, as they are not shown visually the correct number of *currently selected* images.

2. Please see the following screenshot: 

screen shot 2018-07-19 at 5 15 55 pm

When I use the "clear button", found on top of the input, this happens - the image-preview pane gets shrunk. I think this is because of the `width: 29.615861214%;` that is set by `&__image-multi-preview`. It seems like it's being set whether or not the `showMultiple` option is being set. Of course, it should only be set when `showMultiple` is true and there are more then 1 image selected. Scanning the code, I see that you are essentially do this exactly, but there must be a bug somewhere.

3. Please make sure the readme is updated to include the new feature.

4. Please see the following screenshot: 

screen shot 2018-07-19 at 5 16 12 pm

In this case, I selected 2 files, but one of them was a non-standard image file, a .tiff. When a non-standard image file is selected, the backup base-64 encoded images are shown in place, so the user can at least see that their file was selected successfully. I'd like this pull-request to include this support, as this is something that was essential to the concept from the start when I wrote it. Please see `file-upload-with-preview.js` line 98 and the following lines, where I deal with this. This is going to be tricky, as this pull-request changes things up a bit on the logic of the application in that spot.

Great job - I really like this - let's address these issues so we can get this merged. I know it seems like a lot, but these are all critical bugs - and that's to be expected from such a large feature upgrade. Thank you.

**Comment by kozintsev** [comment]
Thank you for the feedback. I will try to correct mistakes in the near future

**Comment by kozintsev** [comment]
I fixed some errors, working with non-standard images in the process.

**Comment by kozintsev** [comment]
Done. I'm waiting for feedback.

2018-07-24 13_54_20-file-upload-with-preview _ promosis

**Comment by deniseileen** [comment]
Thanks for fixing these issues.  Before we pull in this pull request, there is one last bug that needs to be solved.  The input and the image grid are not syncing up with the cached file array.  The problem is that if someone selects 2 files and then opens the picker again and selects 2 more files, the input and image grid both show 4 files, whereas the cached file array when inspected only shows the last 2 files selected.  Ideally we'd like to be able to have the cached file array also show 4 files, but either way the three need to be synchronized so that a user is not expecting 4 files to be uploaded when only 2 are actually being uploaded. 
screen shot 2018-07-26 at 10 52 29 am

**Comment by kozintsev** [comment]
@DeniseWalter Done. I fixed it.

**Comment by deniseileen** [comment]
Ok great!  We did find one tiny remnant bug with the single image uploader input now showing an increased count if you select more than once, but we are going to merge in your pull request and then fix that ourselves.  Thanks again for all your work, this is a great new feature to have.  We'll be releasing a new version on npm soon at version 2.1. In the coming days we're going to be making some more updates to the code, so keep an eye out for that as well.

**Comment by deniseileen** [comment]
@kozintsev, it's updated on npm now at 2.1.0

**Pull request merged**
