### PR TITLE
`imageSelected` event

### PR DESCRIPTION
**Pull request by firstor**
Added an event `imageSelected`.

**Why required?**
I needed to get the file once it's selected and I was not sure when I have to get `cachedFileArray`.
I tried to subscribe `onchange` event on file input, however `cachedFileArray` gave me nothing, since the property can be set after `onchange` is handled inside this module.

### CODE REVIEW

**Comment by firstor** [comment]
@lex111 Could you review this PR? And I also expect your support for this, @johndatserakis

**Review by lex111 — APPROVED** [review]
LGTM :+1:

**Comment by johndatserakis** [comment]
Looks good - thank you for reviewing @lex111. Thanks for the pull-request @firstor. Will be pushing live on npm shortly.

**Comment by firstor** [comment]
Thanks @lex111 @johndatserakis 
BTW, I made a mistake during the update of `README.md`, and I fixed it with the PR #8.

**Pull request merged**
